name: ogrenflutter
description: "Flutter Öğreniyorum - Flutter ve Dart öğrenme yolculuğunu takip eden eğitim uygulaması"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8
  shared_preferences: ^2.2.2
  flutter_markdown: ^0.7.7
  flutter_highlight: ^0.7.0
  percent_indicator: ^4.2.3
  flutter_staggered_grid_view: ^0.7.0
  url_launcher: ^6.2.4
  google_fonts: ^6.1.0
  path_provider: ^2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.1


flutter:
  uses-material-design: true


  assets:
    - assets/questions/
    - assets/content/week_1/


flutter_launcher_icons:
  android: true
  ios: true
  web:
    generate: true
    image_path: "icon.png"
  windows:
    generate: true
    image_path: "icon.png"
  macos:
    generate: true
    image_path: "icon.png"
  linux:
    generate: true
    image_path: "icon.png"
  image_path: "icon.png"
